# SPDX-License-Identifier: AGPL-3.0-or-later
"""Private podcast feed: a real RSS 2.0 feed (iTunes tags) per podcast-enabled
user at /podcast/<token>/feed.xml — the token is the per-user secret minted by
`pipeline.podcast enable`, so the URL itself is the auth (standard practice
for private/member feeds). Subscribe by URL in any podcast app; episodes are
served from the data dir. During the engine trial each day carries two items,
[Anchor] and [NLM].
"""
from __future__ import annotations

import datetime as dt
import email.utils
import json
from pathlib import Path
from xml.sax.saxutils import escape

from fastapi import APIRouter
from fastapi.responses import FileResponse, Response

from app import db
from app.config import cfg, db_path

router = APIRouter()

ENGINE_LABEL = {"anchor": "Anchor", "nlm": "NLM"}


def _user_by_token(con, token: str):
    if not token or len(token) < 16:
        return None
    return con.execute(
        "SELECT * FROM users WHERE podcast_token=? AND podcast_token != ''",
        (token,)).fetchone()


def _rfc2822(iso: str) -> str:
    try:
        return email.utils.format_datetime(dt.datetime.fromisoformat(iso))
    except ValueError:
        return email.utils.formatdate(localtime=True)


def build_feed(con, user, token: str) -> str:
    base = cfg("BASE_URL").rstrip("/")
    feed_url = f"{base}/podcast/{token}"
    cover = f"{base}/static/podcast-cover.png"
    name = user["name"] or user["email"]
    episodes = con.execute(
        "SELECT * FROM podcast_episodes WHERE user_id=? AND status='ok' "
        "ORDER BY date DESC, engine LIMIT 60", (user["id"],)).fetchall()
    items = []
    for e in episodes:
        label = ENGINE_LABEL.get(e["engine"], e["engine"])
        title = f"[{label}] {e['title']}"
        url = f"{feed_url}/ep/{e['id']}.{ 'mp3' if e['mime'] == 'audio/mpeg' else 'wav' }"
        mins, secs = divmod(e["duration_sec"], 60)
        items.append(f"""
    <item>
      <title>{escape(title)}</title>
      <guid isPermaLink="false">papersradar-ep-{e['id']}</guid>
      <pubDate>{_rfc2822(e['created_at'])}</pubDate>
      <enclosure url="{escape(url)}" length="{e['bytes']}" type="{e['mime']}"/>
      <itunes:duration>{mins}:{secs:02d}</itunes:duration>
      <description><![CDATA[{e['shownotes_html']}]]></description>
    </item>""")
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>Papers Radar — {escape(name)}</title>
    <link>{escape(base)}</link>
    <language>en-us</language>
    <description>Private daily audio briefing of new research papers matched
      to this listener's profile. Generated by Papers Radar.</description>
    <itunes:author>Papers Radar</itunes:author>
    <itunes:image href="{escape(cover)}"/>
    <itunes:block>Yes</itunes:block>
    <itunes:explicit>false</itunes:explicit>{''.join(items)}
  </channel>
</rss>
"""


@router.get("/podcast/{token}/feed.xml")
def feed(token: str):
    con = db.connect()
    try:
        user = _user_by_token(con, token)
        if not user:
            return Response(status_code=404)
        return Response(build_feed(con, user, token),
                        media_type="application/rss+xml")
    finally:
        con.close()


@router.get("/podcast/{token}/ep/{episode_id}.{ext}")
def episode(token: str, episode_id: int, ext: str):
    con = db.connect()
    try:
        user = _user_by_token(con, token)
        if not user:
            return Response(status_code=404)
        e = con.execute(
            "SELECT * FROM podcast_episodes WHERE id=? AND user_id=? "
            "AND status='ok'", (episode_id, user["id"])).fetchone()
        if not e or not e["audio_path"]:
            return Response(status_code=404)
        f = db_path().parent / e["audio_path"]
        if not f.exists():
            return Response(status_code=404)
        return FileResponse(str(f), media_type=e["mime"],
                            filename=f"{e['date']}_{e['engine']}{f.suffix}")
    finally:
        con.close()


@router.get("/podcast/{token}/chapters/{episode_id}.json")
def chapters(token: str, episode_id: int):
    """Podcast-Namespace-style chapters JSON (some apps read these when ID3
    chapters are absent — e.g. the WAV fallback)."""
    con = db.connect()
    try:
        user = _user_by_token(con, token)
        if not user:
            return Response(status_code=404)
        e = con.execute(
            "SELECT chapters_json FROM podcast_episodes WHERE id=? AND user_id=?",
            (episode_id, user["id"])).fetchone()
        if not e:
            return Response(status_code=404)
        chs = [{"startTime": c["start_sec"], "title": c["title"]}
               for c in json.loads(e["chapters_json"] or "[]")]
        return Response(json.dumps({"version": "1.2.0", "chapters": chs}),
                        media_type="application/json+chapters")
    finally:
        con.close()
